### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by tergarsam** [adyanth/openwrt-tailscale-enabler#18]
When I do the installation of tailscale on openwrt, after getting to "opkg install libustream-openssl ca-bundle kmod-tun", I get the following message:
Multiple packages that provide the same name (libgcc1 and libgcc1) are marked as HOLD or PREFER. use the latest.
The package libustream-openssl20201210 (2022-01-16-868fd881-1), installed in the root directory, is up to date.
The package ca-bundle (20211016-1) installed in the root directory is up to date.
The package kmod-tun (5.15.46-1), installed in the root directory, is up to date.
Collected errors.
 * pkg_hash_check_unresolved: cannot find dependency kernel (= 5.10.131-1-cf749d8daf0bdc1e420cbc608ee57b33) for kmod-tun

Please, how should I fix it?

Thank you very much!

**Comment by adyanth** [comment]
Looks to be an issue with OpenWRT, please check the FAQ
https://openwrt.org/faq/cannot_satisfy_dependencies
