### ISSUE TITLE
Failed to connect to local tailscaled error

### ISSUE THREAD

**Issue by sunyoung1** [adyanth/openwrt-tailscale-enabler#19]
Hi, i followed your installation guide but i'm ending with this error but both tailscale and tailscaled are running

root@R3:~# tailscale up --accept-dns=false --advertise-routes=10.0.0.0/24
Downloading 'https://pkgs.tailscale.com/stable/'
Connecting to 167.172.11.40:443
Writing to stdout

Download completed (22865 bytes)
Downloading Tailscale 1.28.0_mipsle ..
Downloading 'https://pkgs.tailscale.com/stable/tailscale_1.28.0_mipsle.tgz'
Connecting to 167.172.11.40:443
Writing to stdout
tailscale_1.28.0_mipsle/tailscale

-                     29% |*********                      |  5296k  0:00:09 ETAtailscale_1.28.0_mipsle/tailscaled
-                    100% |*******************************| 17680k  0:00:00 ETA

Download completed (18105167 bytes)
Done!
failed to connect to local tailscaled; it doesn't appear to be running (sudo systemctl start tailscaled ?)

root@R3:~# ps | grep tailscale
 3675 root      1312 S    grep tailscale
 
root@R3:~# ps | grep tailscaled
 3677 root      1312 S    grep tailscaled

**Comment by adyanth** [comment]
I do not see the tailscaled running in your ps output. Try starting the service? To troubleshoot, you can just run `tailscaled` and see if it comes up just fine.
