### ISSUE TITLE
How do i uninstall it?

### ISSUE THREAD

**Issue by ravi23git** [adyanth/openwrt-tailscale-enabler#26]
Hi,

How do i remove it from the system? I worked successfully for me. But somehow, it gets frequently disconnected, i supposed it being removed from RAM. So i compiled, a smaller binary (~5 Mb) using official guide and transferred it over scp to openwrt. when i run tailscale, i get an error "failed to connect to local tailscaled; it doesn't appear to be running". 

I believe i need to undo the changes made by this script and delete the tunnel and then run tailscale again. So far, i have deleted the tar package, tailscale(d).
Please inform, how can i undo the changes made by this script and start afresh?

**Comment by adyanth** [comment]
There is nothing much to remove. Just disable the init.d service from running on boot (and reboot if needed) and you are good to go.
