### ISSUE TITLE
Disable auto-update

### ISSUE THREAD

**Issue by zawee-admin** [adyanth/openwrt-tailscale-enabler#27]
Hi there @adyanth,

Thanks for your work, its all working well on my Teltonika RUTX OpenWRT routers.

How can I disable the auto-update? I'd prefer to update tailscale manually as these devices are in the field.

Thanks

James

**Comment by adyanth** [comment]
Removing these lines below will get you that behavior.
https://github.com/adyanth/openwrt-tailscale-enabler/blob/f433061545db16cf7a9baf73f064f19b17b63c27/usr/bin/tailscale#L19-L22

Then, this line will set the version:
https://github.com/adyanth/openwrt-tailscale-enabler/blob/f433061545db16cf7a9baf73f064f19b17b63c27/usr/bin/tailscale#L17

**Comment by zawee-admin** [comment]
awesome thanks

**Comment by adyanth** [comment]
Remember to do the same on the tailscaled file as well!
