### ISSUE TITLE
it's keep downloading tailscale

### ISSUE THREAD

**Issue by malikshi** [adyanth/openwrt-tailscale-enabler#32]
i skimmed through your code, it seems to download the latest version every time reboots or does the command tailscale [cmd] after reboot.
at first i set per readme `tailscale up --accept-dns=false --advertise-routes=192.168.1.0/24` everything went fine. rebooting devices and i want to change to `tailscale up --accept-dns=false --advertise-routes=192.168.1.0/24 --advertise-exit-node` is downloading assets again.

what's happen if connection are lost while downloading when we aren't at office/home where openwrt installed to

**Comment by adyanth** [comment]
The point of this project is to run from RAM, which means it has to download the binary on reboot. It only downloads the binaries needed, which means on reboot, only the `tailscaled` is downloaded. If you run a command, then the `tailscale` will be downloaded along with `tailscaled` if it wasn't already done.

If you do not have internet, tailscale cannot work either. The only edge case is when the router reboots without internet, in which case you would have to fix it manually. 

There is no easy way to fix this other than an infinite loop waiting for internet, which I did not feel like adding without enough testing. PRs welcome if you think that is helpful.
