### ISSUE TITLE
Everytime reboot openwrt, tailscale can't work

### ISSUE THREAD

**Issue by Yumega** [adyanth/openwrt-tailscale-enabler#34]
/etc/init.d/tailscale enable  (has enabled)

but Everytime reboot openwrt, the Tailscale admin panel shows openwrt connected (iphone also connected), but my iphone can't connect with openwrt.
but after use this 
 tailscale up 
/etc/init.d/tailscale start
It can connect again.

is there a method to restart tailscale one more time after openwrt rebooted?

**Comment by Yumega** [comment]
zerotier doesn't have the problem

**Comment by adyanth** [comment]
If the tail scale admin panel shows the device as connected, there is nothing I can suggest to troubleshoot. You should have better luck checking in tail scale or openwrt forums.

**Comment by Cykaihappy** [comment]
i met the same trouble .when i restart the tailsacel, tailscale visit https://pkgs.tailscale.com/stable/tailscale_1.46.0_arm64.tgz ,and than reponse 404,
![image](https://github.com/adyanth/openwrt-tailscale-enabler/assets/48118769/4b721f5c-623c-46ae-bb04-eddd2f4651cb)

**Comment by adyanth** [comment]
<img width="1012" alt="Screenshot 2023-07-22 at 9 07 25 AM" src="https://github.com/adyanth/openwrt-tailscale-enabler/assets/33192449/8f96a1a0-1480-45f4-a73b-22fad36f33f0">

Looks like 1.46.0 arm64 packages are not yet released.
