### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by lxx12445** [adyanth/openwrt-tailscale-enabler#36]
There's a mistake in DNS after my openwrt reboot firstly.

**Comment by adyanth** [comment]
Could you please elaborate on the issue?

**Comment by lxx12445** [comment]
Hello.The following is the problem's detail.My os is Istoreos(based on lede,x86)(https://www.istoreos.com/).In the beginning,I installed tailscale under the guidance of the article on the website(https://blog.51cto.com/fxn2025/5482046).After the installation was complete,it works normally.However,after I rebooted my computer,dns sever was broken.After I pinged github.com and www.baidu.com,it just replyed:'bad address.'That is all.Because my Istoreos is uninstalled,I have no logs.Thank you for your reply.

**Comment by adyanth** [comment]
This looks more to be a configuration issue. If the tailscale config mismatches with openwrt, it might not be able to access the network.
