### ISSUE TITLE
Kenapa downloadingnya ke versi tailscale 1.52.1 ? padahal sy instal tgz dari link update terbaru ?

### ISSUE THREAD

**Issue by ikbalgodi** [adyanth/openwrt-tailscale-enabler#40]
tailscale up --accept-dns=true --advertise-routes=192.168.51.0/24 --accept-routes=true --advertise-exit-node=true --ssh=true 
Downloading 'https://pkgs.tailscale.com/stable/'
Connecting to 199.38.181.239:443
Writing to stdout

Download completed (36668 bytes)
Downloading Tailscale 1.52.1_mipsle ..
Downloading 'https://pkgs.tailscale.com/stable/tailscale_1.52.1_mipsle.tgz'
Connecting to 199.38.181.239:443
Redirected to /stable/tailscale_1.52.1_mipsle.tgz on dl.tailscale.com
Connection error: Connection failed
tar: invalid magic

**Comment by adyanth** [comment]
Please try with the latest version
