### ISSUE TITLE
Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status

### ISSUE THREAD

**Issue by nkxhl** [adyanth/openwrt-tailscale-enabler#43]
failed to connect to local tailscaled (which appears to be running as tailscaled, pid 4544). Got error: Failed to connect to local Tailscale daemon for /localapi/v0/status; not running? Error: dial unix /var/run/tailscale/tailscaled.sock: connect: no such file or directory

**Comment by adyanth** [comment]
Is this consistent? Have you managed to fix it?
