### ISSUE TITLE
I have followed your steps for the installation, if for some reason I need to uninstall completely?

### ISSUE THREAD

**Issue by 6025278** [adyanth/openwrt-tailscale-enabler#47]

**Comment by adyanth** [comment]
This installs 3 files, `/usr/bin/tailscale`, `/usr/bin/tailscaled`, `/etc/init.d/tailscale`. Please delete these, and optionally the `/tmp/tailscale*` contents created for storing the binaries

**Comment by varac** [comment]
There's also the state directory at `/var/lib/tailscale` which can be deleted on uninstall
