### ISSUE TITLE
Warning: client version "1.32.3-1 (OpenWrt)" != tailscaled server version "1.74.1-tccd6bf2f4-g8fce4ce11"

### ISSUE THREAD

**Issue by HaoBanLu** [adyanth/openwrt-tailscale-enabler#55]
**When I execute the command:**
tailscale up --accept-dns=false --advertise-routes=192.168.10.0/24

**Prompt warning**
Warning: client version "1.32.3-1 (OpenWrt)" != tailscaled server version "1.74.1-tccd6bf2f4-g8fce4ce11"

**Current environment:**
istoreos

**Comment by BJReplay** [comment]
You have installed the opkg tailscale at some point, and also attempted to install this version.  You need to remove the opkg version before attempting to install this version.

**Comment by HaoBanLu** [comment]
> You have installed the opkg tailscale at some point, and also attempted to install this version. You need to remove the opkg version before attempting to install this version.

Thank you, you are right, follow the steps you said, I succeed
