### ISSUE TITLE
How to persist openwrt-tailscale-enabler

### ISSUE THREAD

**Issue by fgfg163** [adyanth/openwrt-tailscale-enabler#57]
This script downloads tailscale to /tmp directory, which is in memory. This is a solution for small flash or read-only flash devices. So after reboot you need to re-download tailscale.

If the device has enough storage space, you can change the download path to /root/ or somewhere else to avoid re-downloading every time you restart.

Check `/usr/bin/tailscale` and `/usr/bin/tailscaled`, replace the path `/tmp` with `/root/tailscale` or other path, restart the device, and manually start the script again. Tailscale will be downloaded to the ROM and automatically enabled after restart.

**Comment by adyanth** [comment]
If you have enough space, please use the official opkg package: https://openwrt.org/docs/guide-user/services/vpn/tailscale/start
